# Generated by Django 4.0.5 on 2022-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectSee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to='profiles')),
                ('Bio', models.TextField(max_length=500)),
                ('contacts', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='projects')),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
