# Generated by Django 4.0.5 on 2022-06-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectSee', '0004_alter_profile_user_alter_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
    ]
