# Generated by Django 4.0.5 on 2022-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectSee', '0009_remove_newsletterrecipients_user_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user1.png', null=True, upload_to='profiles'),
        ),
    ]
